import type { NextPage } from "next";
import Head from "next/head";
import { Screen } from "components/common/Screen";
import { Config, ViscousScroller } from "components/ViscousScroller";
import { useEffect, useMemo, useState } from "react";

const SCREEN_COLORS = [
  "#00FF00",
  "#00FFFF",
  "#0000FF",
  "#FFFF00",
  "#FF00FF",
  "#FF0000",
];

const STEP_FREEZE = 500;

const Home: NextPage = () => {
  const [config, setConfig] = useState<Config>([]);

  useEffect(() => {
    const cfg: Config = [];
    const viewportHeight = window.innerHeight;
    for (let i = 0; i < SCREEN_COLORS.length; i++) {
      cfg.push(
        { toY: (i + 1) * viewportHeight + i * STEP_FREEZE, mode: "scroll" },
        {
          toY: (i + 1) * viewportHeight + i * STEP_FREEZE + STEP_FREEZE,
          mode: "freeze",
        }
      );
    }
    setConfig(cfg);
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {config.length && (
          <ViscousScroller scrollConfig={config}>
            {SCREEN_COLORS.map((color) => (
              <Screen key={color} color={color} />
            ))}
          </ViscousScroller>
        )}
      </main>
    </div>
  );
};

export default Home;
